language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script:
  - phpunit -c app

notifications:
  email:
    -  renanciciliato@gmail.com