imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pt_BR
    setor_fotos: '%kernel.root_dir%/../web/uploads/setores'
framework:
    #esi: ~
    translator: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
    assets: ~
# Twig Configuration
twig:
    debug: '%kernel.debug%'
    form_themes:
        - "bootstrap_3_layout.html.twig"
    strict_variables: '%kernel.debug%'
# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
# Doctrine Migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/AppBundle/Migrations"
    namespace: AppBundle\Migrations
    table_name: migrations
    name: SGMC Migrations
    organize_migrations: "BY_YEAR_AND_MONTH"
    # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
# VicHUploader configuration
vich_uploader:
    db_driver: orm
    mappings:
        setor_img:
            uri_prefix: /uploads/setores
            upload_destination: '%kernel.root_dir%/../web/uploads/setores'
            namer: vich_uploader.namer_uniqid
        equip_img:
            uri_prefix: /uploads/equip
            upload_destination: '%kernel.root_dir%/../web/uploads/equip'
            namer: vich_uploader.namer_uniqid
# Assetic configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
# LiipImagine configuration
liip_imagine:
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    # your filter sets are defined here
    filter_sets:
        # use the default cache config
        cache: ~
        # name of filter set
        app_thumb:
            # adjust quality to 75%
            quality: 75
            # list transformations to apply
            filters:
                # thumbnail
                thumbnail: { size: [120, 90], mode: outbound }
                # 2px border black
                backgroud: { size: [124, 94], position: center, color: '#000000' }