logout:
    path: /logout

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_adm:
    resource: '@AppBundle/Controller/Admin'
    type: annotation

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'