security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin, roles: ROLE_USER }