security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
    providers:
        db:
            entity:
                class: AppBundle:Usuario
                property: usuario
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout
                target: /
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
    #access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin, roles: ROLE_USER }