security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory:
            memory: ~
        database:
            entity:
                class: AppBundle:User
                property: username
    firewalls:        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            anonymous: ~        
        main:            
            pattern: ^/admin
            form_login:
                login_path: login
                check_path: login
            provider: database            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }