security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
    providers:
        in_memory:
            memory: ~
        database_users:
            entity:
                class: AppBundle:Usuario,
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/admin
            form_login:
                csrf_token_generator: security.csrf.token_manager
                check_path: login
                login_path: login
            logout:
                path: logout
                target: home
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }